### ISSUE TITLE
Any guide on how to setup for xenforo latest 

### ISSUE THREAD

**Issue by billyprice1old** [alexxpert/xenforo-android-client#1]
Any guide on how to setup for xenforo latest

**Comment by libalex** [comment]
Just get [bd] API plugin [here](https://xenforo.com/community/resources/bd-api.1732/), add client ID in your forum's CP and set your forum URL [here](https://github.com/alexxpert/xenforo-android-client/blob/9e91b7130a68afe549626446da288b178a4b80f3/app/src/main/java/ru/worldjb/android/api/API.java#L40)
